export enum SubraceType {
  None = 'None',
  Meadow_Human = 'Meadow_Human',
  Ocean_Human = 'Ocean_Human',
  Savannah_Human = 'Savannah_Human',
  Wood_Elf = 'Wood_Elf',
  Snow_Elf = 'Snow_Elf',
  Mountain_Dwarf = 'Mountain_Dwarf',
  Boreal_Dwarf = 'Boreal_Dwarf',
  Death_Godlike = 'Death_Godlike',
  Fire_Godlike = 'Fire_Godlike',
  Nature_Godlike = 'Nature_Godlike',
  Moon_Godlike = 'Moon_Godlike',
  Hearth_Orlan = 'Hearth_Orlan',
  Wild_Orlan = 'Wild_Orlan',
  Coastal_Aumaua = 'Coastal_Aumaua',
  Island_Aumaua = 'Island_Aumaua',
  Avian_Godlike = 'Avian_Godlike',
  Advanced_Construct = 'Advanced_Construct',
  Marine_Godlike = 'Marine_Godlike',
  Meadow_Savannah_Human = 'Meadow_Savannah_Human',
  Storm_Human = 'Storm_Human',
  Drunk_Orlan = 'Drunk_Orlan',
  Endings_Godlike = 'Endings_Godlike',
}
