export enum PermittedEquipmentSlot {
  None = 'None',
  Head = 'Head',
  Neck = 'Neck',
  Cape = 'Cape',
  Armor = 'Armor',
  RingAnyHand = 'RingAnyHand',
  RingRightHand = 'RingRightHand',
  RingLeftHand = 'RingLeftHand',
  Hand = 'Hand',
  Feet = 'Feet',
  Waist = 'Waist',
  GrimoireOrTrinket = 'GrimoireOrTrinket',
  AnyWeapon = 'AnyWeapon',
  PrimaryWeaponOnly = 'PrimaryWeaponOnly',
  SecondaryWeaponOnly = 'SecondaryWeaponOnly',
  BothPrimaryAndSecondary = 'BothPrimaryAndSecondary',
  Pet = 'Pet',
  Prop = 'Prop',
}
